### ISSUE TITLE
Creating TopicGroups via ExtensionContext

### ISSUE THREAD

**Issue by Blafasel3** [hivemq/hivemq-swarm-extension-sdk#26]
## Problem or use case
We are creating dynamic subscriptions in the form of `topicprefix/<id>/topicsuffix` where `id` is a specific domain value.
We would like to create `topicGroups` via Code using a `com.hivemq.swarm.extension.sdk.ExtensionMain` extension. This is as far as I can tell not possible, the only way to generate this behavior is to generate a xml scenario programmitically which basically requires a two step solution (1. create xml File dynamically, 2. Run Scenario) and makes the management of topics rather difficult because there is no obvious link between the xml-File scenario configuration and the extension code.

## Preferred solution or suggestions
I imagine that the XML files entities are parsed into Java Objects anyhow, so the same object creation would have to be exposed on the `ExtensionContext` in some way or the other.

**Comment by YannickWeber** [comment]
Hello Blafasel3,

thank you for feature request. Sadly, your requested feature would require a very big restructure to how HiveMQ Swarm generates topic strings and distributes them among the agents.

But, maybe you can use Swarm's ability to pass your scenario as velocity template: https://docs.hivemq.com/swarm/4.18/swarm/commands.html#:~:text=Variable-,Use,-in%20a%20Velocity

- Yannick
